2018-02-04 16:11:40,052 - src.web - INFO - Parseada [1]
2018-02-04 16:11:40,057 - src.web - INFO - Parseada [2]
2018-02-04 16:11:40,059 - src.web - INFO - Parseada[4]
2018-02-04 16:11:40,063 - src.web - INFO - Parseada[3]
2018-02-04 16:20:48,801 - src.web - INFO - Parseada [1]
2018-02-04 16:20:48,805 - src.web - INFO - Parseada [2]
2018-02-04 16:20:48,808 - src.web - INFO - Parseada[4]
2018-02-04 16:20:48,813 - src.web - INFO - Parseada[3]
2018-02-04 21:48:35,825 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x108c86dd8>
2018-02-04 21:48:35,827 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 21:48:35,828 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517809715, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x108c61598>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x107728358>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 21:51:07,983 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x107653d30>
2018-02-04 21:51:45,868 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x108faed30>
2018-02-04 21:52:01,671 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x10bc15d68>
2018-02-04 21:52:01,672 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 21:52:24,713 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x103eb5d30>
2018-02-04 21:52:24,715 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 21:52:24,715 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517809944, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x103e84510>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x102898320>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 21:53:47,757 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x10fa47cc0>
2018-02-04 21:53:47,759 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 21:53:47,759 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810027, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x10fa16510>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x10e4b5320>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 21:57:29,005 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x10bc97898>
2018-02-04 21:57:29,006 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 21:57:29,006 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810249, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x10bc6b2f0>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x10a74a828>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 21:59:00,530 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x10d2a6860>
2018-02-04 21:59:00,531 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 21:59:00,531 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810340, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x10d27a2f0>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x10bd59828>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 22:03:00,569 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x1031457f0>
2018-02-04 22:03:00,571 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:03:00,571 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810580, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x1031112f0>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x101bf0828>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 22:03:16,085 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x108d81860>
2018-02-04 22:03:16,087 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:03:16,087 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810596, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x108d552f0>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x107834828>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 22:04:13,482 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x109788898>
2018-02-04 22:04:13,483 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:04:13,483 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810653, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x10975b2f0>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x10823a828>, 'from': {'id': 1, 'first_name': 'John', 'type': '', 'last_name': '', 'username': ''}}}
2018-02-04 22:05:55,193 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x106ed0828>
2018-02-04 22:05:55,195 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:05:55,195 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810755, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x106ea32f0>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x105982860>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:06:05,385 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x108860898>
2018-02-04 22:06:05,387 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:06:05,387 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810765, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x1088342f0>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x107313860>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:06:49,947 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x1032d18d0>
2018-02-04 22:06:49,948 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:06:49,948 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517810809, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x1032a4378>, 'text': '\\start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x1032478d0>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:20:58,957 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x10698b908>
2018-02-04 22:20:58,959 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:20:58,959 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517811658, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x10695e2f0>, 'text': '/start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x105422048>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:24:24,125 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x109da6898>
2018-02-04 22:24:24,126 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:24:24,126 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517811864, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x109d792f0>, 'text': '/start@ujohn', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x108858860>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:24:56,062 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x10878c940>
2018-02-04 22:25:14,757 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:25:46,406 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517811896, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x1087612f0>, 'text': '/start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x107224080>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:26:21,859 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x106b92908>
2018-02-04 22:26:23,970 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:26:23,971 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517811981, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x106b662f0>, 'text': '/start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x105629080>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:26:31,821 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x11096d908>
2018-02-04 22:26:40,144 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:26:43,320 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517811991, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x1109412f0>, 'text': '/start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x10f41f080>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:30:13,651 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x110eee908>
2018-02-04 22:30:15,584 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:30:15,585 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517812213, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x110ec2268>, 'text': '/start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x10f985080>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:30:15,585 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'staticmethod' object is not callable
2018-02-04 22:30:55,949 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x104807908>
2018-02-04 22:30:55,950 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-04 22:30:55,951 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 4, 'message': {'message_id': 3, 'date': 1517812255, 'chat': {'id': 2, 'type': 'private', 'title': '', 'username': 'ujohn', 'first_name': 'john', 'last_name': '', 'all_members_are_admins': False}, 'reply_to_message': <function BotTest.dummyCb at 0x1047db268>, 'text': '/start', 'entities': [], 'caption': '', 'new_chat_title': '', 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'reply_text': <staticmethod object at 0x1031ea048>, 'from': {'id': 1, 'first_name': 'john', 'type': '', 'last_name': '', 'username': 'ujohn'}}}
2018-02-04 22:30:55,951 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'staticmethod' object is not callable
2018-02-04 22:31:07,014 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x1053a48d0>
2018-02-04 22:31:07,015 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'staticmethod' object is not callable
2018-02-06 21:54:26,311 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x1027aa8d0>
2018-02-06 21:54:26,313 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'staticmethod' object is not callable
2018-02-06 21:55:06,782 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x103d928d0>
2018-02-06 21:55:06,783 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'staticmethod' object is not callable
2018-02-06 21:55:34,017 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x111823898>
2018-02-06 21:55:34,018 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'staticmethod' object is not callable
2018-02-06 21:55:46,479 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x1095bf860>
2018-02-06 21:55:46,480 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'staticmethod' object is not callable
2018-02-06 21:57:09,395 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x1109b5898>
2018-02-06 22:03:01,672 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 52, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 96, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
2018-02-06 22:04:43,311 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x106e44860>
2018-02-06 22:04:44,499 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
TypeError: 'NoneType' object is not callable
2018-02-06 22:04:48,109 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10a6a68d0>
2018-02-06 22:05:44,396 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
2018-02-06 22:05:45,778 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x1034ef860>
2018-02-06 22:12:25,121 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x106b63ba8>
2018-02-06 22:12:25,122 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 99, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 75, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:12:31,640 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10291aba8>
2018-02-06 22:12:31,641 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 99, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 75, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:12:49,139 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x105549c18>
2018-02-06 22:12:49,140 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 100, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 75, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:13:18,172 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x11132dbe0>
2018-02-06 22:13:18,173 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 101, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 76, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:13:34,881 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10e907b70>
2018-02-06 22:13:34,882 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 103, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 78, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:13:50,870 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x107fc8be0>
2018-02-06 22:13:50,871 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 104, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 79, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:14:09,796 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10e6b0ba8>
2018-02-06 22:14:09,797 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 105, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 79, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:14:37,947 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x103ec4c18>
2018-02-06 22:14:37,948 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 105, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 79, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:14:54,991 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10e461c18>
2018-02-06 22:14:54,991 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 69, in start
    update.message.reply_text(self._START_MSG % name)
  File "test/bot_test.py", line 105, in <lambda>
    cb_check = lambda x: self.contains(expected, x)
  File "test/bot_test.py", line 79, in contains
    self.assertTrue(expected_string in received_string)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-02-06 22:16:12,545 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x104005be0>
2018-02-06 22:17:26,576 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10d09cc18>
2018-02-06 22:17:35,793 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10a5d7be0>
2018-02-06 22:18:40,270 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x1111c2c50>
2018-02-06 22:20:09,865 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x10f521c88>
2018-02-06 22:20:47,855 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x108eefc50>
2018-02-06 22:21:10,235 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x11166cc18>
2018-02-06 22:21:21,607 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x102ae6be0>
2018-02-06 22:21:56,303 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x103749b38>
2018-02-06 22:22:41,274 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x108ae4ba8>
2018-02-06 22:22:54,890 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x104aeebe0>
2018-02-06 22:24:00,856 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <__main__.MockDispatcher object at 0x11060ac88>
2018-02-06 22:24:00,862 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,062 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <src.test.bot_test.MockDispatcher object at 0x10ca66ef0>
2018-02-15 18:44:12,063 - src.bot - INFO - Get 1
2018-02-15 18:44:12,070 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,075 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,078 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,081 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,082 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/fmontoto/Projects/bot-valevista/src/bot.py", line 102, in set_rut
    rut = Rut.build_rut(spl[1])
IndexError: list index out of range
2018-02-15 18:44:12,088 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,092 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,096 - src.bot - INFO - User 21 set rut 2343234
2018-02-15 18:44:12,099 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as None
2018-02-15 18:44:12,226 - src.model_interface - ERROR - (sqlite3.IntegrityError) UNIQUE constraint failed: subscribed_users.user_id [SQL: 'INSERT INTO subscribed_users (user_id, chat_id) VALUES (?, ?)'] [parameters: (1, 5658)]
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: subscribed_users.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/src/model_interface.py", line 42, in commit_rollback
    session_.commit()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: subscribed_users.user_id [SQL: 'INSERT INTO subscribed_users (user_id, chat_id) VALUES (?, ?)'] [parameters: (1, 5658)]
2018-02-15 18:44:12,247 - src.model_interface - ERROR - (sqlite3.IntegrityError) UNIQUE constraint failed: subscribed_users.chat_id [SQL: 'INSERT INTO subscribed_users (user_id, chat_id) VALUES (?, ?)'] [parameters: (2, 5657)]
Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: subscribed_users.chat_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fmontoto/Projects/bot-valevista/src/model_interface.py", line 42, in commit_rollback
    session_.commit()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/fmontoto/Projects/bot-valevista/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: subscribed_users.chat_id [SQL: 'INSERT INTO subscribed_users (user_id, chat_id) VALUES (?, ?)'] [parameters: (2, 5657)]
2018-02-15 18:44:12,254 - src.web - DEBUG - Parsed cliente.
2018-02-15 18:44:12,261 - src.web - INFO - [<src.web.Event object at 0x10ca14208>, <src.web.Event object at 0x10cd539e8>, <src.web.Event object at 0x10cd53a90>]
2018-02-15 18:44:12,261 - src.web - DEBUG - Parsed pagina no disponible.
2018-02-15 18:44:12,262 - src.web - DEBUG - Parsed pagina vacia.
